services:
# Database
  postgres:
    image: postgres:17
    container_name: yorkmedical-postgres
    environment:
      POSTGRES_DB: yorkmedical
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  # Use local folder for data persistence
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d yorkmedical"]
      interval: 5s
      timeout: 3s
      retries: 5

# API
  springboot:
    build:
      context: ./springboot
      dockerfile: Dockerfile
    container_name: yorkmedical-backend
    ports:
      - "8080:8080"
    environment:
      # Auth
      OAUTH2_ISSUER:
      OAUTH2_CLIENT_ID:
      OAUTH2_CLIENT_SECRET:

      # Database
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/yorkmedical
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      postgres:
        condition: service_healthy

# React SPA
  react:
    build:
      context: ./react
      dockerfile: Dockerfile
    container_name: yorkmedical-frontend
    ports:
      # - "80:80"
      - "3000:3000"
    depends_on:
      - springboot